apiVersion: v1
kind: Service
metadata:
  name: node-test
spec:
  type: NodePort
  ports:
    - port: 8981
      nodePort: 30002
  selector:
    app: node-test
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: node-test
spec:
  replicas: 2
  selector:
    app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
      - name: node-test
        image: fish.co:8001/node-test:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8981